# Generated by Django 4.2.20 on 2025-10-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_employee_number_alter_user_center_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_reservations_per_day",
            field=models.PositiveIntegerField(
                default=1, verbose_name="حداکثر رزرو در روز"
            ),
        ),
    ]
