# Generated by Django 4.2.20 on 2025-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_max_reservations_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_guest_reservations_per_day",
            field=models.PositiveIntegerField(
                default=1, verbose_name="حداکثر رزرو مهمان در روز"
            ),
        ),
    ]
