# Generated by Django 4.2.20 on 2025-10-21 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام غذا")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="meals/", verbose_name="تصویر"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "غذا",
                "verbose_name_plural": "غذاها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MealType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام وعده")),
                ("start_time", models.TimeField(verbose_name="زمان شروع")),
                ("end_time", models.TimeField(verbose_name="زمان پایان")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "نوع وعده",
                "verbose_name_plural": "انواع وعده",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField(verbose_name="تاریخ شروع هفته")),
                ("week_end_date", models.DateField(verbose_name="تاریخ پایان هفته")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centers.center",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه هفتگی",
                "verbose_name_plural": "برنامه\u200cهای هفتگی",
                "ordering": ["-week_start_date"],
                "unique_together": {("center", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "max_reservations",
                    models.PositiveIntegerField(
                        default=100, verbose_name="حداکثر تعداد رزرو"
                    ),
                ),
                (
                    "current_reservations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد رزروهای فعلی"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="در دسترس"),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_management.meal",
                        verbose_name="غذا",
                    ),
                ),
                (
                    "meal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_management.mealtype",
                        verbose_name="نوع وعده",
                    ),
                ),
                (
                    "weekly_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_menus",
                        to="food_management.weeklymenu",
                        verbose_name="برنامه هفتگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "منوی روزانه",
                "verbose_name_plural": "منوهای روزانه",
                "ordering": ["date", "meal_type__start_time"],
                "unique_together": {("weekly_menu", "date", "meal_type")},
            },
        ),
        migrations.CreateModel(
            name="FoodReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ رزرو"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "رزرو شده"),
                            ("cancelled", "لغو شده"),
                            ("served", "سرو شده"),
                        ],
                        default="reserved",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "cancellation_deadline",
                    models.DateTimeField(verbose_name="مهلت لغو"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ لغو"
                    ),
                ),
                (
                    "daily_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_management.dailymenu",
                        verbose_name="منوی روزانه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "رزرو غذا",
                "verbose_name_plural": "رزروهای غذا",
                "ordering": ["-reservation_date"],
                "unique_together": {("user", "daily_menu")},
            },
        ),
        migrations.CreateModel(
            name="FoodReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="تاریخ گزارش")),
                (
                    "total_reservations",
                    models.PositiveIntegerField(default=0, verbose_name="کل رزروها"),
                ),
                (
                    "total_served",
                    models.PositiveIntegerField(default=0, verbose_name="کل سرو شده"),
                ),
                (
                    "total_cancelled",
                    models.PositiveIntegerField(default=0, verbose_name="کل لغو شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centers.center",
                        verbose_name="مرکز",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش غذا",
                "verbose_name_plural": "گزارش\u200cهای غذا",
                "ordering": ["-report_date"],
                "unique_together": {("center", "report_date")},
            },
        ),
    ]
