# Generated by Django 5.2.7 on 2025-10-21 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_phone'),
        ('food_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['title'], 'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.AlterUniqueTogether(
            name='foodreservation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='meal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.mealtype', verbose_name='وعده'),
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.mealtype', verbose_name='وعده'),
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رستوران'),
        ),
        migrations.AddField(
            model_name='meal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='تصویر')),
                ('publish_date', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='daily_menu',
        ),
    ]
