# Generated by Django 5.2.7 on 2025-10-21 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_phone'),
        ('food_management', '0002_alter_meal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodreservation',
            unique_together={('user', 'date', 'meal_type', 'center')},
        ),
    ]
