# Generated by Django 4.2.20 on 2025-10-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_management", "0003_alter_foodreservation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodreservation",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="تعداد رزرو"),
        ),
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
