# Generated by Django 4.2.20 on 2025-10-22 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0002_alter_center_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_management", "0004_foodreservation_quantity_delete_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_first_name",
                    models.CharField(max_length=150, verbose_name="نام مهمان"),
                ),
                (
                    "guest_last_name",
                    models.CharField(max_length=150, verbose_name="نام خانوادگی مهمان"),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "رزرو شده"),
                            ("cancelled", "لغو شده"),
                            ("served", "سرو شده"),
                        ],
                        default="reserved",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="مبلغ"
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ رزرو"),
                ),
                (
                    "cancellation_deadline",
                    models.DateTimeField(verbose_name="مهلت لغو"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ لغو"
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centers.center",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "host_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر میزبان",
                    ),
                ),
                (
                    "meal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_management.mealtype",
                        verbose_name="وعده",
                    ),
                ),
            ],
            options={
                "verbose_name": "رزرو مهمان",
                "verbose_name_plural": "رزروهای مهمان",
                "ordering": ["-reservation_date"],
                "unique_together": {
                    (
                        "host_user",
                        "date",
                        "meal_type",
                        "center",
                        "guest_first_name",
                        "guest_last_name",
                    )
                },
            },
        ),
    ]
