# Generated by Django 5.2.7 on 2025-10-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_phone'),
        ('food_management', '0005_guestreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز'),
        ),
    ]
