# Generated by Django 5.2.7 on 2025-10-23 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0006_meal_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-created_at'], 'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.AlterModelOptions(
            name='mealtype',
            options={'ordering': ['start_time'], 'verbose_name': 'نوع وعده', 'verbose_name_plural': 'انواع وعده\u200cها'},
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='current_reservations',
            field=models.PositiveIntegerField(default=0, verbose_name='رزروهای فعلی'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='max_reservations',
            field=models.PositiveIntegerField(default=100, verbose_name='حداکثر رزرو'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_management.mealtype', verbose_name='وعده'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='restaurant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رستوران'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
