# Generated by Django 5.2.7 on 2025-10-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0007_alter_meal_options_alter_mealtype_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodreservation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='guestreservation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='current_reservations',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='max_reservations',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='meal',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='max_reservations_per_meal',
            field=models.PositiveIntegerField(default=100, verbose_name='حداکثر رزرو برای هر غذا'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='meals',
            field=models.ManyToManyField(blank=True, to='food_management.meal', verbose_name='غذاهای موجود'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='daily_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.dailymenu', verbose_name='منوی روزانه'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.meal', verbose_name='غذا'),
        ),
        migrations.AddField(
            model_name='guestreservation',
            name='daily_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.dailymenu', verbose_name='منوی روزانه'),
        ),
        migrations.AddField(
            model_name='guestreservation',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.meal', verbose_name='غذا'),
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='center',
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='guestreservation',
            name='center',
        ),
        migrations.RemoveField(
            model_name='guestreservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='guestreservation',
            name='meal_type',
        ),
    ]
