# Generated by Django 5.2.7 on 2025-11-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_phone'),
        ('food_management', '0008_alter_foodreservation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='guestreservation',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='meal',
        ),
        migrations.CreateModel(
            name='BaseMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز')),
                ('meal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.mealtype', verbose_name='وعده')),
            ],
            options={
                'verbose_name': 'غذای پایه',
                'verbose_name_plural': 'غذاهای پایه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان غذا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='گزینه پیش\u200cفرض')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('base_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='food_management.basemeal', verbose_name='گروه غذا')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='meal_options',
            field=models.ManyToManyField(blank=True, related_name='daily_menus', to='food_management.mealoption', verbose_name='غذاهای موجود'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.mealoption', verbose_name='گزینه غذا'),
        ),
        migrations.AddField(
            model_name='guestreservation',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.mealoption', verbose_name='گزینه غذا'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام رستوران')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='centers.center', verbose_name='مرکز')),
            ],
            options={
                'verbose_name': 'رستوران',
                'verbose_name_plural': 'رستوران\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mealoption',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_options', to='food_management.restaurant', verbose_name='رستوران'),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
