# Generated by Django 5.2.7 on 2025-11-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0009_remove_dailymenu_meals_remove_guestreservation_meal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealoption',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='basemeal',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_meals', to='food_management.restaurant', verbose_name='رستوران'),
        ),
    ]
