# Generated by Django 5.2.7 on 2025-11-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0010_remove_mealoption_restaurant_basemeal_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeal',
            name='cancellation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت لغو'),
        ),
    ]
