# Generated by Django 5.2.7 on 2025-11-02 03:55

import django.db.models.deletion
from django.db import migrations, models


def copy_center_from_weekly_menu(apps, schema_editor):
    """کپی کردن center از weekly_menu به center"""
    DailyMenu = apps.get_model('food_management', 'DailyMenu')
    for daily_menu in DailyMenu.objects.filter(center__isnull=True):
        if daily_menu.weekly_menu:
            daily_menu.center = daily_menu.weekly_menu.center
            daily_menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_phone'),
        ('food_management', '0011_basemeal_cancellation_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز'),
        ),
        migrations.RunPython(copy_center_from_weekly_menu, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together={('center', 'date', 'meal_type')},
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='weekly_menu',
        ),
        migrations.DeleteModel(
            name='WeeklyMenu',
        ),
    ]
