# Generated by Django 5.2.7 on 2025-11-02 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_phone'),
        ('food_management', '0012_remove_weekly_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز'),
        ),
    ]
