# Generated by Django 5.2.7 on 2025-11-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0013_make_center_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealoption',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد موجود'),
        ),
    ]
