# Generated by Django 5.2.7 on 2025-11-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0014_mealoption_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealoption',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد رزرو شده'),
        ),
    ]
