# Generated by Django 5.2.7 on 2025-11-02 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_phone'),
        ('food_management', '0015_mealoption_reserved_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealoption',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/', verbose_name='تصویر')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('restaurant', models.CharField(blank=True, max_length=200, null=True, verbose_name='رستوران')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز')),
                ('meal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_management.mealtype', verbose_name='وعده')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='تاریخ شروع هفته')),
                ('week_end_date', models.DateField(verbose_name='تاریخ پایان هفته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه\u200cهای هفتگی',
                'ordering': ['-week_start_date'],
                'unique_together': {('center', 'week_start_date')},
            },
        ),
    ]
