# Generated by Django 5.2.8 on 2025-11-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_center_english_name'),
        ('food_management', '0016_alter_mealoption_quantity_meal_weeklymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='basemeal',
            name='meal_type',
        ),
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'ordering': ['date'], 'verbose_name': 'منوی روزانه', 'verbose_name_plural': 'منوهای روزانه'},
        ),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together={('center', 'date')},
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='meal_type',
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
    ]
