# Generated by Django 5.2.8 on 2025-11-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0017_remove_meal_meal_type_remove_basemeal_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='daily_menu_info',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات منوی روزانه (حذف شده)'),
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='meal_option_info',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات غذا (حذف شده)'),
        ),
        migrations.AddField(
            model_name='guestreservation',
            name='daily_menu_info',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات منوی روزانه (حذف شده)'),
        ),
        migrations.AddField(
            model_name='guestreservation',
            name='meal_option_info',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات غذا (حذف شده)'),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='daily_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dailymenu', verbose_name='منوی روزانه'),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.mealoption', verbose_name='گزینه غذا'),
        ),
        migrations.AlterField(
            model_name='guestreservation',
            name='daily_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dailymenu', verbose_name='منوی روزانه'),
        ),
        migrations.AlterField(
            model_name='guestreservation',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.mealoption', verbose_name='گزینه غذا'),
        ),
    ]
