# Generated by Django 5.2.8 on 2025-11-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0018_foodreservation_daily_menu_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='base_meals',
            field=models.ManyToManyField(blank=True, related_name='daily_menus', to='food_management.basemeal', verbose_name='غذاهای پایه'),
        ),
    ]
