# Generated by Django 5.2.8 on 2025-11-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0019_dailymenu_base_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='meal_options',
        ),
        migrations.CreateModel(
            name='DailyMenuMealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان غذا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد رزرو شده')),
                ('is_default', models.BooleanField(default=False, verbose_name='گزینه پیش\u200cفرض')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('base_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu_options', to='food_management.basemeal', verbose_name='غذای پایه')),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_meal_options', to='food_management.dailymenu', verbose_name='منوی روزانه')),
            ],
            options={
                'verbose_name': 'اپشن غذا برای منو',
                'verbose_name_plural': 'اپشن\u200cهای غذا برای منو',
                'ordering': ['sort_order', 'title'],
                'unique_together': {('daily_menu', 'base_meal', 'title')},
            },
        ),
    ]
