# Generated by Django 5.2.8 on 2025-11-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0021_change_dailymenu_center_to_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_management.restaurant', verbose_name='رستوران'),
        ),
    ]
