# Generated by Django 5.2.8 on 2025-11-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0022_alter_dailymenu_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemeal',
            name='cancellation_deadline',
        ),
        migrations.AddField(
            model_name='dailymenumealoption',
            name='cancellation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت لغو'),
        ),
    ]
