# Generated by Django 5.2.8 on 2025-11-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0023_remove_basemeal_cancellation_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealoption',
            name='base_meal',
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dailymenumealoption', verbose_name='گزینه غذا'),
        ),
        migrations.AlterField(
            model_name='guestreservation',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dailymenumealoption', verbose_name='گزینه غذا'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklymenu',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='center',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealOption',
        ),
        migrations.DeleteModel(
            name='WeeklyMenu',
        ),
    ]
