# Generated by Django 5.2.8 on 2025-11-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_center_english_name'),
        ('food_management', '0024_remove_mealoption_base_meal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='center',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='centers',
            field=models.ManyToManyField(related_name='restaurants', to='centers.center', verbose_name='مراکز'),
        ),
    ]
