# Generated by Django 5.2.8 on 2025-11-22 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_center_english_name'),
        ('food_management', '0025_remove_restaurant_center_restaurant_centers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='desserts/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desserts', to='food_management.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'دسر',
                'verbose_name_plural': 'دسرها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenuDessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد رزرو شده')),
                ('is_default', models.BooleanField(default=False, verbose_name='گزینه پیش\u200cفرض')),
                ('cancellation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت لغو')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_desserts', to='food_management.dailymenu', verbose_name='منوی روزانه')),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu_desserts', to='food_management.dessert', verbose_name='دسر')),
            ],
            options={
                'verbose_name': 'دسر برای منو',
                'verbose_name_plural': 'دسرهای منو',
                'ordering': ['sort_order', 'title'],
                'unique_together': {('daily_menu', 'dessert', 'title')},
            },
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='desserts',
            field=models.ManyToManyField(blank=True, related_name='daily_menus', to='food_management.dessert', verbose_name='دسرها'),
        ),
        migrations.CreateModel(
            name='DessertReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_menu_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات منوی روزانه (حذف شده)')),
                ('dessert_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات دسر (حذف شده)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد رزرو')),
                ('status', models.CharField(choices=[('reserved', 'رزرو شده'), ('cancelled', 'لغو شده'), ('served', 'سرو شده')], default='reserved', max_length=20, verbose_name='وضعیت')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ رزرو')),
                ('cancellation_deadline', models.DateTimeField(verbose_name='مهلت لغو')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('daily_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dailymenu', verbose_name='منوی روزانه')),
                ('dessert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dailymenudessert', verbose_name='دسر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شناسه کاربر')),
            ],
            options={
                'verbose_name': 'رزرو دسر',
                'verbose_name_plural': 'رزروهای دسر',
                'ordering': ['-reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='GuestDessertReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(max_length=150, verbose_name='نام مهمان')),
                ('guest_last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی مهمان')),
                ('daily_menu_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات منوی روزانه (حذف شده)')),
                ('dessert_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات دسر (حذف شده)')),
                ('status', models.CharField(choices=[('reserved', 'رزرو شده'), ('cancelled', 'لغو شده'), ('served', 'سرو شده')], default='reserved', max_length=20, verbose_name='وضعیت')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ رزرو')),
                ('cancellation_deadline', models.DateTimeField(verbose_name='مهلت لغو')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('daily_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dailymenu', verbose_name='منوی روزانه')),
                ('dessert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dailymenudessert', verbose_name='دسر')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر میزبان')),
            ],
            options={
                'verbose_name': 'رزرو دسر مهمان',
                'verbose_name_plural': 'رزروهای دسر مهمان',
                'ordering': ['-reservation_date'],
            },
        ),
    ]
