# Generated by Django 5.2.8 on 2025-11-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0026_dessert_dailymenudessert_dailymenu_desserts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeal',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='محتویات'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='محتویات'),
        ),
    ]
