# Generated by Django 5.2.8 on 2025-11-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0027_basemeal_ingredients_dessert_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
    ]
