# Generated by Django 5.2.8 on 2025-11-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0028_remove_restaurant_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemeal',
            name='center',
        ),
    ]
