# Generated by Django 5.2.8 on 2025-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0029_remove_basemeal_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestreservation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
