# Generated by Django 5.2.8 on 2025-11-24 20:04
# Modified to include data migration with raw SQL

import django.db.models.deletion
from django.db import migrations, models


def migrate_dailymenudessert_to_dessert(apps, schema_editor):
    """Migrate data from DailyMenuDessert to Dessert and update reservations using raw SQL"""
    db_alias = schema_editor.connection.alias
    
    # Step 1: Update Dessert records with data from DailyMenuDessert using raw SQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE food_management_dessert d
            SET price = md.price,
                quantity = md.quantity,
                reserved_quantity = md.reserved_quantity
            FROM food_management_dailymenudessert md
            WHERE md.dessert_id = d.id
        """)
    
    # Step 2: Update DessertReservation to point to Dessert instead of DailyMenuDessert using raw SQL
    with schema_editor.connection.cursor() as cursor:
        # First, drop the ForeignKey constraint temporarily
        cursor.execute("""
            ALTER TABLE food_management_dessertreservation
            DROP CONSTRAINT IF EXISTS food_management_dess_dessert_id_3393319a_fk_food_mana
        """)
        
        # Update dessert_id to point to Dessert instead of DailyMenuDessert
        cursor.execute("""
            UPDATE food_management_dessertreservation dr
            SET dessert_id = md.dessert_id
            FROM food_management_dailymenudessert md
            WHERE dr.dessert_id = md.id AND md.dessert_id IS NOT NULL
        """)
        
        # Set to NULL if DailyMenuDessert doesn't exist or has no dessert
        cursor.execute("""
            UPDATE food_management_dessertreservation dr
            SET dessert_id = NULL
            WHERE dr.dessert_id IS NOT NULL
            AND NOT EXISTS (
                SELECT 1 FROM food_management_dailymenudessert md
                WHERE md.id = dr.dessert_id
            )
        """)
    
    # Step 3: Update GuestDessertReservation to point to Dessert instead of DailyMenuDessert using raw SQL
    with schema_editor.connection.cursor() as cursor:
        # First, drop the ForeignKey constraint temporarily
        cursor.execute("""
            ALTER TABLE food_management_guestdessertreservation
            DROP CONSTRAINT IF EXISTS food_management_gues_dessert_id_8d4001a1_fk_food_mana
        """)
        
        # Update dessert_id to point to Dessert instead of DailyMenuDessert
        cursor.execute("""
            UPDATE food_management_guestdessertreservation gdr
            SET dessert_id = md.dessert_id
            FROM food_management_dailymenudessert md
            WHERE gdr.dessert_id = md.id AND md.dessert_id IS NOT NULL
        """)
        
        # Set to NULL if DailyMenuDessert doesn't exist or has no dessert
        cursor.execute("""
            UPDATE food_management_guestdessertreservation gdr
            SET dessert_id = NULL
            WHERE gdr.dessert_id IS NOT NULL
            AND NOT EXISTS (
                SELECT 1 FROM food_management_dailymenudessert md
                WHERE md.id = gdr.dessert_id
            )
        """)


def reverse_migrate_dessert_to_dailymenudessert(apps, schema_editor):
    """Reverse migration - not fully reversible"""
    # This is complex to reverse, so we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0030_guestreservation_description'),
    ]

    operations = [
        # Step 1: Add new fields to Dessert
        migrations.AddField(
            model_name='dessert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد رزرو شده'),
        ),
        # Step 2: Migrate data from DailyMenuDessert to Dessert (updates dessert_id in reservations)
        # This uses raw SQL to drop constraints, update data, then Django will recreate constraints
        migrations.RunPython(migrate_dailymenudessert_to_dessert, reverse_migrate_dessert_to_dailymenudessert),
        # Step 3: Change ForeignKey in DessertReservation and GuestDessertReservation
        # Note: The dessert_id values have already been updated in step 2, and constraints were dropped
        migrations.AlterField(
            model_name='dessertreservation',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dessert', verbose_name='دسر'),
        ),
        migrations.AlterField(
            model_name='guestdessertreservation',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_management.dessert', verbose_name='دسر'),
        ),
        # Step 4: Delete DailyMenuDessert model
        migrations.DeleteModel(
            name='DailyMenuDessert',
        ),
    ]
