# Generated by Django 5.2.8 on 2025-11-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_remove_center_address_remove_center_city_and_more'),
        ('food_management', '0032_change_dessert_fk_remove_dailymenudessert'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='مرکز'),
        ),
    ]
