# Generated by Django 5.2.8 on 2025-11-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0039_basedessert_alter_dailymenu_base_desserts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basedessert',
            options={'ordering': ['-created_at'], 'verbose_name': 'دسر پایه', 'verbose_name_plural': 'دسرهای پایه'},
        ),
        migrations.RemoveField(
            model_name='basedessert',
            name='center',
        ),
        migrations.AlterField(
            model_name='basedessert',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_desserts', to='food_management.restaurant', verbose_name='رستوران'),
        ),
        migrations.AlterModelTable(
            name='basedessert',
            table='food_management_dessert',
        ),
    ]
