# Generated by Django 5.2.8 on 2025-11-29 16:59
# Modified to handle case where table might not exist or field already removed

import django.db.models.deletion
from django.db import migrations, models, connection


def remove_center_field_if_exists(apps, schema_editor):
    """حذف فیلد center فقط در صورت وجود جدول و فیلد"""
    db_table = 'food_management_dessert'  # نام واقعی جدول در دیتابیس
    
    with connection.cursor() as cursor:
        # بررسی وجود جدول
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [db_table])
        
        table_exists = cursor.fetchone()[0]
        
        if table_exists:
            # بررسی وجود فیلد center
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s 
                    AND column_name = 'center_id'
                );
            """, [db_table])
            
            field_exists = cursor.fetchone()[0]
            
            if field_exists:
                # حذف foreign key constraint اگر وجود دارد
                try:
                    cursor.execute("""
                        SELECT constraint_name 
                        FROM information_schema.table_constraints 
                        WHERE table_schema = 'public' 
                        AND table_name = %s 
                        AND constraint_type = 'FOREIGN KEY'
                        AND constraint_name LIKE %s
                    """, [db_table, '%center%'])
                    
                    constraints = cursor.fetchall()
                    for constraint in constraints:
                        constraint_name = constraint[0]
                        cursor.execute(f'ALTER TABLE {db_table} DROP CONSTRAINT IF EXISTS {constraint_name};')
                except Exception:
                    pass
                
                # حذف فیلد
                cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN IF EXISTS center_id;')


def reverse_remove_center_field(apps, schema_editor):
    """برگرداندن فیلد center (در صورت نیاز)"""
    # این عملیات reverse نمی‌شود چون فیلد center دیگر استفاده نمی‌شود
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0039_basedessert_alter_dailymenu_base_desserts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basedessert',
            options={'ordering': ['-created_at'], 'verbose_name': 'دسر پایه', 'verbose_name_plural': 'دسرهای پایه'},
        ),
        # استفاده از RunPython برای حذف امن فیلد
        migrations.RunPython(
            remove_center_field_if_exists,
            reverse_remove_center_field,
        ),
        migrations.AlterField(
            model_name='basedessert',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_desserts', to='food_management.restaurant', verbose_name='رستوران'),
        ),
        migrations.AlterModelTable(
            name='basedessert',
            table='food_management_dessert',
        ),
    ]
