# Generated by Django 5.2.9 on 2025-12-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0040_alter_basedessert_options_remove_basedessert_center_and_more'),
    ]

    operations = [
        # این migration الان خالی است چون center field در migration 0040 حذف شده است
        # برای حفظ ترتیب migration ها این فایل را نگه می‌داریم
    ]
