# Generated by Django 5.2.9 on 2025-12-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0040_alter_basedessert_options_remove_basedessert_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedessert',
            name='center',
        ),
    ]
