# Generated by Django 5.2.9 on 2025-12-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0041_remove_basedessert_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='base_desserts',
            field=models.ManyToManyField(blank=True, related_name='daily_menus', to='food_management.basedessert', verbose_name='دسرهای پایه'),
        ),
    ]
