# Generated by Django 5.2.7 on 2025-10-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
