# Generated by Django 5.2.8 on 2025-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
