# Generated by Django 5.2.8 on 2025-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_center_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='centers/logos/'),
        ),
    ]
