# Generated by Django 5.2.8 on 2025-11-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_center_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='address',
        ),
        migrations.RemoveField(
            model_name='center',
            name='city',
        ),
        migrations.RemoveField(
            model_name='center',
            name='email',
        ),
        migrations.RemoveField(
            model_name='center',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='center',
            name='phone',
        ),
    ]
