# Generated by Django 5.2.8 on 2025-12-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_remove_center_address_remove_center_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
