# Generated by Django 5.2.8 on 2025-11-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_center_english_name'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='center',
        ),
        migrations.AddField(
            model_name='announcement',
            name='centers',
            field=models.ManyToManyField(related_name='announcements', to='centers.center', verbose_name='مراکز'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='lead',
            field=models.TextField(blank=True, help_text='توضیحات کوتاه که در ابتدای خبر نمایش داده می\u200cشود', max_length=500, null=True, verbose_name='لید خبر (توضیحات کوتاه)'),
        ),
    ]
