# Generated by Django 5.2.9 on 2025-12-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_create_story_centers_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='centers',
        ),
    ]
