# Generated by Django 5.2.9 on 2025-12-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_center_english_name_alter_center_name'),
        ('hr', '0009_story_expiry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_announcement',
            field=models.BooleanField(default=False, verbose_name='به عنوان اطلاعیه منتشر شود'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_news',
            field=models.BooleanField(default=False, verbose_name='به عنوان خبر منتشر شود'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='فقط برای اطلاعیه: انتخاب یک یا چند کاربر خاص', related_name='targeted_announcements', to=settings.AUTH_USER_MODEL, verbose_name='کاربران خاص'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='centers',
            field=models.ManyToManyField(blank=True, help_text='برای خبر و اطلاعیه: انتخاب یک یا چند مرکز', related_name='announcements', to='centers.center', verbose_name='مراکز'),
        ),
        migrations.CreateModel(
            name='AnnouncementReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خوانده شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='hr.announcement', verbose_name='اطلاعیه/خبر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_read_statuses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وضعیت خوانده شده اطلاعیه',
                'verbose_name_plural': 'وضعیت\u200cهای خوانده شده اطلاعیه\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
