# Generated by Django 5.2.9 on 2025-12-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_announcement_is_announcement_announcement_is_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_users',
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_to_all_users',
            field=models.BooleanField(default=False, help_text='فقط برای اطلاعیه: اگر فعال باشد، به همه کاربران ارسال می\u200cشود', verbose_name='ارسال به کل کاربران'),
        ),
    ]
