# Generated by Django 5.2.9 on 2025-12-30 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_remove_announcement_target_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='فقط برای اطلاعیه: انتخاب یک یا چند کاربر خاص (در صورت عدم انتخاب send_to_all_users)', related_name='targeted_announcements', to=settings.AUTH_USER_MODEL, verbose_name='کاربران خاص'),
        ),
    ]
