version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: compose/prod/Dockerfile
    command: sh /app/compose/prod/django-entrypoint.sh
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:
